/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ros_rosjava_tutorial_native_node_MoveBaseNativeNode */

#ifndef _Included_org_ros_rosjava_tutorial_native_node_MoveBaseNativeNode
#define _Included_org_ros_rosjava_tutorial_native_node_MoveBaseNativeNode
#ifdef __cplusplus
extern "C" {
#endif
#undef org_ros_rosjava_tutorial_native_node_MoveBaseNativeNode_SUCCESS
#define org_ros_rosjava_tutorial_native_node_MoveBaseNativeNode_SUCCESS 0L
/*
 * Class:     org_ros_rosjava_tutorial_native_node_MoveBaseNativeNode
 * Method:    execute
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_ros_rosjava_1tutorial_1native_1node_MoveBaseNativeNode_execute
  (JNIEnv *, jobject, jstring, jstring, jstring, jobjectArray);

/*
 * Class:     org_ros_rosjava_tutorial_native_node_MoveBaseNativeNode
 * Method:    shutdown
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ros_rosjava_1tutorial_1native_1node_MoveBaseNativeNode_shutdown
  (JNIEnv *, jobject);

/*
 * Class:     org_ros_rosjava_tutorial_native_node_MoveBaseNativeNode
 * Method:    setCancelGoals
 * Signature: ()I
 */
JNIEXPORT void JNICALL Java_org_ros_rosjava_1tutorial_1native_1node_MoveBaseNativeNode_setCancelGoals
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
