/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ros_rosjava_tutorial_native_node_FasterLioNativeNode */

#ifndef _Included_org_ros_rosjava_tutorial_native_node_FasterLioNativeNode
#define _Included_org_ros_rosjava_tutorial_native_node_FasterLioNativeNode
#ifdef __cplusplus
extern "C" {
#endif
#undef org_ros_rosjava_tutorial_native_node_FasterLioNativeNode_SUCCESS
#define org_ros_rosjava_tutorial_native_node_FasterLioNativeNode_SUCCESS 0L
/*
 * Class:     org_ros_rosjava_tutorial_native_node_FasterLioNativeNode
 * Method:    executeNative
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_ros_rosjava_1tutorial_1native_1node_FasterLioNativeNode_executeNative
  (JNIEnv *, jobject, jstring, jstring, jstring, jobjectArray);

/*
 * Class:     org_ros_rosjava_tutorial_native_node_FasterLioNativeNode
 * Method:    shutdownNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ros_rosjava_1tutorial_1native_1node_FasterLioNativeNode_shutdownNative
  (JNIEnv *, jobject);

/*
 * Class:     org_ros_rosjava_tutorial_native_node_FasterLioNativeNode
 * Method:    prepareNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_ros_rosjava_1tutorial_1native_1node_FasterLioNativeNode_prepareNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
