/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ros_rosjava_tutorial_native_node_LsmNativeNode */

#ifndef _Included_org_ros_rosjava_tutorial_native_node_LsmNativeNode
#define _Included_org_ros_rosjava_tutorial_native_node_LsmNativeNode
#ifdef __cplusplus
extern "C" {
#endif
#undef org_ros_rosjava_tutorial_native_node_LsmNativeNode_SUCCESS
#define org_ros_rosjava_tutorial_native_node_LsmNativeNode_SUCCESS 0L
/*
 * Class:     org_ros_rosjava_tutorial_native_node_LsmNativeNode
 * Method:    execute
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_ros_rosjava_1tutorial_1native_1node_LsmNativeNode_execute
  (JNIEnv *, jobject, jstring, jstring, jstring, jobjectArray);

/*
 * Class:     org_ros_rosjava_tutorial_native_node_LsmNativeNode
 * Method:    shutdown
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ros_rosjava_1tutorial_1native_1node_LsmNativeNode_shutdown
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
